version: "3.3"

networks:
  default:
    external:
      name: reverse_proxy_admin

services:
  jukebox-front:
    image: registry.siroz.ovh/jukebox-front:latest
    restart: always
    container_name: jukebox-front
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jukebox.rule=Host(`siroz.ovh`)"
      - "traefik.http.routers.jukebox.entrypoints=web"
      - "traefik.http.services.jukebox.loadbalancer.server.port=80"
      - "traefik.docker.network=reverse_proxy_admin"
