version: "3.3"

networks:
  default:
    external:
      name: reverse_proxy_gateway

services:
  jukebox-front:
    image: registry.siroz.ovh/jukebox-front:latest
    restart: always
    container_name: jukebox-front
    labels:
      - "traefik.enable=true"
      # Router HTTP -> HTTPS
      - "traefik.http.routers.jukebox-http.rule=Host(`40.pain-pain.altidoma.ch`)"
      - "traefik.http.routers.jukebox-http.entrypoints=web"
      - "traefik.http.routers.jukebox-http.middlewares=jukebox-https@docker"
      - "traefik.http.middlewares.jukebox-https.redirectscheme.scheme=https"
      # Router HTTPS
      - "traefik.http.routers.jukebox.rule=Host(`40.pain-pain.altidoma.ch`)"
      - "traefik.http.routers.jukebox.entrypoints=websecure"
      - "traefik.http.routers.jukebox.tls=true"
      - "traefik.http.routers.jukebox.tls.certresolver=letsencrypt"
      # Service
      - "traefik.http.services.jukebox.loadbalancer.server.port=80"
      # Middleware final sur HTTPS
      - "traefik.docker.network=reverse_proxy_gateway"

